export const ITALY_GRID_SQUARES = [
  "JM39",
  "JM48",
  "JM49",
  "JM66",
  "JM67",
  "JM68",
  "JM69",
  "JM76",
  "JM77",
  "JM78",
  "JM79",
  "JM86",
  "JM87",
  "JM88",
  "JM89",
  "JM97",
  "JM98",
  "JN34",
  "JN35",
  "JN36",
  "JN37",
  "JN40",
  "JN41",
  "JN44",
  "JN45",
  "JN46",
  "JN47",
  "JN51",
  "JN52",
  "JN53",
  "JN54",
  "JN55",
  "JN56",
  "JN57",
  "JN60",
  "JN61",
  "JN62",
  "JN63",
  "JN64",
  "JN65",
  "JN66",
  "JN67",
  "JN70",
  "JN71",
  "JN72",
  "JN76",
  "JN80",
  "JN81",
];

export const TIPOLOGIA_MAP: Record<string, string | null> = {
  "FM": "ANALOG",
  "fm": "ANALOG",
  "DMR": "DMR",
  "C4FM": "C4FM",
  "DS": "DSTAR",
  "EL": "ECHOLINK",
  "SVX": "SVX",
  "SVXLink": "SVX",
  "SWXLink": "SVX",
  "ATV": "ATV",
  "Beacon": "BEACON",
  "LN": "ANALOG",
  "PK": "APRS",
  "NXDN": "NXDN",
  "AllStar": "ALLSTAR",
  "Winlink": "WINLINK",
};

export const RETE_MAP: Record<string, string> = {
  "BrandMeister": "BrandMeister",
  "EchoLink": "EchoLink",
  "Wires-X": "Wires-X",
  "Wires-x": "Wires-X",
  "ADN": "ADN",
  "ircDDB": "ircDDB",
  "IT-DMR": "IT-DMR",
  "DMR+": "DMR+",
  "DMR-Marc": "DMR-Marc",
  "AllStar": "AllStar",
  "YSF": "YSF",
};

export const RETE_SKIP = ["l", ""];
